name: CI/CD Tienda Perritos - Frontend AWS



on:

  push:

    branches: [ "main" ]

    paths:

      - "frontend/**"



jobs:

  build-push-deploy-frontend:

    runs-on: ubuntu-latest



    steps:

    - name: Checkout código

      uses: actions/checkout@v3



    - name: Configurar credenciales AWS

      uses: aws-actions/configure-aws-credentials@v4

      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

        aws-region: ${{ secrets.AWS_REGION }}



    - name: Login en Amazon ECR (runner)

      uses: aws-actions/amazon-ecr-login@v1



    - name: Build imagen Frontend y push a ECR

      run: |

        cd frontend

        docker build -t tienda-frontend .

        docker tag tienda-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

        docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest



    - name: Desplegar Frontend vía SSH directo

      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.EC2_PUBLIC_IP }}

        username: ec2-user

        key: ${{ secrets.EC2_SSH_KEY }}

        port: 22

        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN

        script: |

          set -e

          # 1. Configurar credenciales de AWS dentro de la EC2

          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"

          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

          export AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}"

          export AWS_REGION="us-east-1"

          

          # 2. Invocar tu secreto y extraer automáticamente el dominio de AWS para el login

          REPO_URL="${{ secrets.ECR_REPO_URL_FRONTEND }}"

          REGISTRY_URL=$(echo "$REPO_URL" | cut -d'/' -f1)

          

          # 3. Autenticar Docker de forma segura

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_URL

          

          # 4. Descargar la imagen usando la variable del secreto

          docker pull $REPO_URL:latest

          

          # 5. Refrescar el contenedor en la EC2

          docker stop tienda-frontend || true

          docker rm tienda-frontend || true

          docker run -d --name tienda-frontend -p 80:80 $REPO_URL:latest

          

          # 6. Limpieza de espacio en disco

          docker image prune -f
