name: CI/CD Tienda Perritos - Backend



on:

  push:

    branches: [ "master" ] # Mantenemos tu configuración original de rama

    paths:

      - "backend/**"



jobs:

  build-push-deploy-backend:

    runs-on: ubuntu-latest



    steps:

    - name: Checkout código

      uses: actions/checkout@v3



    - name: Configurar credenciales AWS (Para el Runner)

      uses: aws-actions/configure-aws-credentials@v4

      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

        aws-region: ${{ secrets.AWS_REGION }}



    - name: Login en Amazon ECR (runner)

      uses: aws-actions/amazon-ecr-login@v1



    - name: Build imagen Backend y push a ECR

      run: |

        cd backend

        docker build -t tienda-backend .

        docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest



    - name: Desplegar Backend en Subred Privada vía Bastión (SSH)

      uses: appleboy/ssh-action@v1.0.3

      with:

        # --- DESTINO FINAL: INSTANCIA DE LA APP / BACKEND ---

        host: "10.0.2.144"                          # Tu IP privada fija del Backend

        username: ec2-user

        key: ${{ secrets.EC2_SSH_KEY }}

        port: 22



        # --- EL PUENTE (BASTIÓN): INSTANCIA DEL FRONTEND PÚBLICO ---

        proxy_host: ${{ secrets.EC2_PUBLIC_IP }}     # IP Pública de tu Frontend

        proxy_username: ec2-user

        proxy_key: ${{ secrets.EC2_SSH_KEY }}

        proxy_port: 22



        script: |

          set -e

          

          # 1. Recuperar la URL del repositorio ECR desde tus secretos de GitHub

          REPO_URL="${{ secrets.ECR_REPO_URL_BACKEND }}"

          REGISTRY_URL=$(echo "$REPO_URL" | cut -d'/' -f1)

          

          # 2. Autenticar Docker (La EC2 usa su propio rol LabInstanceProfile internamente)

          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $REGISTRY_URL

          

          # 3. Descargar la última versión de la imagen del Backend (NodeJS)

          docker pull $REPO_URL:latest

          

          # 4. Detener y remover el contenedor anterior si existe

          docker stop tienda-backend || true

          docker rm tienda-backend || true

          

          # 5. Encender el contenedor mapeando el puerto 3001 expuesto en tu Dockerfile

          docker run -d --name tienda-backend -p 3001:3001 $REPO_URL:latest

          

          # 6. Limpieza preventiva de imágenes antiguas en el servidor de la App

          docker image prune -f