name: CI/CD Tienda Perritos - DB con AWS



on:

  push:

    branches: [ "master" ]

    paths:

      - "db/**" # Se activa automáticamente cuando detecta cambios en la carpeta "db"



jobs:

  build-push-deploy-db:

    runs-on: ubuntu-latest



    steps:

    - name: Checkout código

      uses: actions/checkout@v3



    - name: Configurar credenciales AWS (Para el Runner)

      uses: aws-actions/configure-aws-credentials@v4

      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

        aws-region: ${{ secrets.AWS_REGION }}



    - name: Login en Amazon ECR (Runner)

      uses: aws-actions/amazon-ecr-login@v1



    - name: Build imagen DB y push a ECR

      run: |

        cd db

        docker build -t tienda-db .

        docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB }}:latest

        docker push ${{ secrets.ECR_REPO_URL_DB }}:latest



    - name: Desplegar Base de Datos en Subred Privada vía Bastión (SSH)

      uses: appleboy/ssh-action@v1.0.3

      with:

        # --- DESTINO FINAL: INSTANCIA DE LA BASE DE DATOS ---

        host: "10.0.3.17"                          # IP privada fija de tu BD

        username: ec2-user

        key: ${{ secrets.EC2_SSH_KEY }}

        port: 22



        # --- EL PUENTE (BASTIÓN): INSTANCIA DEL FRONTEND PÚBLICO ---

        proxy_host: ${{ secrets.EC2_PUBLIC_IP }}     # IP Pública de tu Frontend

        proxy_username: ec2-user

        proxy_key: ${{ secrets.EC2_SSH_KEY }}

        proxy_port: 22



        script: |

          set -e

          

          # 1. Recuperar la URL del repositorio ECR desde tus secretos de GitHub

          REPO_URL="${{ secrets.ECR_REPO_URL_DB }}"

          REGISTRY_URL=$(echo "$REPO_URL" | cut -d'/' -f1)

          

          # 2. Autenticar Docker (La EC2 usa su rol LabInstanceProfile internamente de forma automática)

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_URL

          

          # 3. Descargar la última versión de la imagen de MySQL

          docker pull $REPO_URL:latest

          

          # 4. Detener y remover el contenedor anterior si existe

          docker stop tienda-db || true

          docker rm tienda-db || true

          

          # 5. Encender el contenedor mapeando el puerto 3306 y manteniendo la persistencia del volumen

          docker run -d --name tienda-db -p 3306:3306 -v dbdata:/var/lib/mysql $REPO_URL:latest

          

          # 6. Limpieza preventiva de espacio en disco en el servidor de la BD

          docker image prune -f

